obj-y									+= dwm3000_init.o
obj-y									+= dwm3000_transceive_test.o
obj-y									+= adhocuwb_init.o
obj-y									+= adhocuwb_swarm_ranging.o
obj-y 									+= adhocuwb_sniffer.o
obj-$(CONFIG_UWB_LOCALIZATION_ENABLE)	+= adhocuwb_control.o
obj-$(CONFIG_UWB_LOCALIZATION_ENABLE)	+= adhocuwb_localization.o
